name: FishingRewards
author: Mahdi_
version: 3.0
main: com.fishingrewards.FishingRewards
api-version: '1.20'
softdepend: [WorldGuard]
commands:
  fishingrewards:
    aliases: [fr, fishingr, frewards]
    description: Primary command for the plugin.
    permission: 'fishingrewards.admin'